services:
  - type: web
    name: kaichat-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: redirect
        source: /*
        destination: /index.html
        status: 200